name: "Build and test"
on:
  pull_request:
    branches:
      - main
    workflow_dispatch:
jobs:
  qa:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: pre-commit/action@v3.0.0
  test:
    timeout-minutes: 10
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "requirements-dev.txt"
      - run: pip install -r requirements-dev.txt
      - run: python -m unittest discover tests/ -v
